# This code is being used to train a model using tweets/users attributes but not NLP or Image Processing

In [5]:
import MySQLdb
import pandas as pd
from Classes.Database import Database
import json
import urllib2
import numpy
import math
import time
import datetime
import os
import os.path
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import average_precision_score

In [6]:
def getimage(url, full_name):
    full_name = "images/" + full_name
    if os.path.isfile(full_name):
        return mpimg.imread(full_name)
    
    try:
        f = urllib2.urlopen(url)
    except:
        return None
    
    data = f.read()
    with open(full_name, "wb") as code:
        code.write(data)
    return mpimg.imread(full_name)
def getallimages(imagesList):
    downloaded_images = []
    for image in imagesList:
        img = getimage(image,image.split('/')[-1])
        downloaded_images.append(img)
    return downloaded_images

In [7]:
engine = Database()

In [8]:
users = pd.read_sql("SELECT screen_name, if(followers_count = 0, 1, followers_count) as followers_count, \
                if(friends_count = 0, 1, friends_count) as friends_count,\
                statuses_count, if(verified, 1, 0) as verified,\
                TIMESTAMPDIFF(YEAR,created_at,CURDATE()) as 'Account Age',\
                klout_score \
                FROM user WHERE klout_score is not null",
                    con = engine.myDB, index_col = 'screen_name')
users

followers_count  friends_count  statuses_count  verified  \
screen_name                                                                 
Lysette_P                    420            401            4787         0   
Gboarders                    386           1021            5804         0   
PabloAcostaTuc              1090            216            2371         0   
patigalafassi                169            170            5386         0   
tricky_dickie87              320           1344             663         0   
joeflech                    3658           1224           11410         1   
MariaLaurita3p               244            648            2415         0   
tjchev_51                    469            518            3867         0   
casadecrews                 2980           1505           30852         0   
tatianaeslava                270            188            3926         0   
neelybeddoe                  593            990            3182         0   
Angel_Rodas19                138            506            1058         0   
kaassanndraa                4766             97            6682         0   
osp1na                       746            131           29042         0   
DLasAmericas              112154          12510          407453         1   
jcscala65                     47            219             233         0   
YBezzy_                     3475           3166           36299         0   
MariaWiliman                  20             60             684         0   
O_Jamison                    153            212             565         0   
OrlPartyInvites              496            432             624         0   
wimmer_pa                    248             84            1292         0   
dgirlinluv                    49             83             110         0   
ChrisPetley                  268            419            5287         0   
letsantanna                 1140            509           31622         0   
anjubeltran                  203             76            1961         0   
ATCCPV                       820           1049            5971         0   
TaCreaciaBlunt              1402           1200           43895         0   
KatFtAV                       91            132            8634         0   
TheBStinger                  349            258            9268         0   
YetsiGabriela                220            282            2737         0   
...                          ...            ...             ...       ...   
DaniellChehab                141            264             459         0   
luisbloomin                   54            289             629         0   
michele_chef                 638           1175            4022         0   
Dorii_Casey                  616            342           22645         0   
RichwayMar                   905            411            9013         0   
MillionBeccs                 800            599            9723         0   
kabongelamech1                32            215             238         0   
adrix1113                    298            408            2552         0   
DavidTwitoMLD                131            189             635         0   
jordanmwakeman               348            335            5372         0   
LizagnaSucks                1791            184           82705         0   
ymorizumi                    607            603            4311         0   
Bobbyc134                    150            423             599         0   
Rell865                      252             77           11346         0   
jthake                     13889           2585           35116         0   
jskripac                      76            470              16         0   
FloydBhere                  1449           1947           21972         0   
WinsomeDame                  343            256            3987         0   
simplyAbysmommy               39             54             899         0   
wa_salcedo   

In [9]:
users.describe()

followers_count  friends_count  statuses_count      verified  \
count     9.613700e+04   96137.000000    9.613700e+04  96137.000000   
mean      3.758839e+03     764.862831    1.055268e+04      0.017600   
std       8.248914e+04    3458.788973    2.442905e+04      0.131493   
min       1.000000e+00       1.000000    1.000000e+00      0.000000   
25%       1.270000e+02     172.000000    7.730000e+02      0.000000   
50%       3.440000e+02     364.000000    3.171000e+03      0.000000   
75%       8.360000e+02     734.000000    1.069100e+04      0.000000   
max       1.178080e+07  455605.000000    2.021478e+06      1.000000   

        Account Age  klout_score  
count  96137.000000      96137.0  
mean       5.590595          0.0  
std        2.512334          0.0  
min        0.000000          0.0  
25%        4.000000          0.0  
50%        6.000000          0.0  
75%        8.000000          0.0  
max       11.000000          0.0

In [10]:
print len(users.loc[users['followers_count'] < 5000])
print len(users.loc[users['friends_count'] < 100])
print len(users.loc[users['statuses_count'] < 100])

91189
13192
6414


In [15]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

myusers = users.copy()
numerical_cols = ['followers_count','friends_count','statuses_count','Account Age','klout_score']


scaler1 = StandardScaler()
scaler2 = StandardScaler()
myusers[numerical_cols] = scaler1.fit_transform(myusers[numerical_cols])
myusers[numerical_cols] = scaler2.fit_transform(myusers[numerical_cols])

In [16]:
myusers

followers_count  friends_count  statuses_count  verified  \
screen_name                                                                 
Lysette_P              -0.040476      -0.105200       -0.236019         0   
Gboarders              -0.040888       0.074054       -0.194388         0   
PabloAcostaTuc         -0.032354      -0.158687       -0.334918         0   
patigalafassi          -0.043519      -0.171987       -0.211498         0   
tricky_dickie87        -0.041689       0.167440       -0.404835         0   
joeflech               -0.001222       0.132746        0.035094         1   
MariaLaurita3p         -0.042610      -0.033787       -0.333117         0   
tjchev_51              -0.039882      -0.071373       -0.273679         0   
casadecrews            -0.009442       0.213988        0.830954         0   
tatianaeslava          -0.042295      -0.166783       -0.271264         0   
neelybeddoe            -0.038379       0.065092       -0.301719         0   
Angel_Rodas19          -0.043895      -0.074842       -0.388666         0   
kaassanndraa            0.012210      -0.193093       -0.158447         0   
osp1na                 -0.036524      -0.183262        0.756862         0   
DLasAmericas            1.314061       3.395755       16.247149         1   
jcscala65              -0.044998      -0.157820       -0.422437         0   
YBezzy_                -0.003441       0.694217        1.053928         0   
MariaWiliman           -0.045325      -0.203790       -0.403975         0   
O_Jamison              -0.043713      -0.159844       -0.408847         0   
OrlPartyInvites        -0.039555      -0.096237       -0.406431         0   
wimmer_pa              -0.042561      -0.196851       -0.379087         0   
dgirlinluv             -0.044974      -0.197140       -0.427472         0   
ChrisPetley            -0.042319      -0.099996       -0.215551         0   
letsantanna            -0.031748      -0.073975        0.862474         0   
anjubeltran            -0.043107      -0.199164       -0.351701         0   
ATCCPV                 -0.035627       0.082150       -0.187551         0   
TaCreaciaBlunt         -0.028572       0.125807        1.364871         0   
KatFtAV                -0.044465      -0.182973       -0.078541         0   
TheBStinger            -0.041337      -0.146544       -0.052588         0   
YetsiGabriela          -0.042901      -0.139605       -0.319936         0   
...                          ...            ...             ...       ...   
DaniellChehab          -0.043859      -0.144809       -0.413186         0   
luisbloomin            -0.044913      -0.137581       -0.406227         0   
michele_chef           -0.037834       0.118579       -0.267334         0   
Dorii_Casey            -0.038100      -0.122258        0.495000         0   
RichwayMar             -0.034597      -0.102309       -0.063027         0   
MillionBeccs           -0.035870      -0.047954       -0.033963         0   
kabongelamech1         -0.045180      -0.158976       -0.422232         0   
adrix1113              -0.041955      -0.103176       -0.327509         0   
DavidTwitoMLD          -0.043980      -0.166493       -0.405981         0   
jordanmwakeman         -0.041349      -0.124282       -0.212072         0   
LizagnaSucks           -0.023856      -0.167939        2.953561         0   
ymorizumi              -0.038209      -0.046798       -0.255504         0   
Bobbyc134              -0.043749      -0.098839       -0.407455         0   
Rell865                -0.042513      -0.198875        0.032475         0   
jthake                  0.122807       0.526238        1.005502         0   
jskripac               -0.044647      -0.085251       -0.431320         0   
FloydBhere             -0.028002       0.341780        0.467451         0   
WinsomeDame            -0.041410      -0.147122       -0.268767         0   
simplyAbysmommy        -0.045095      -0.205525       -0.395174         0   
wa_salcedo   

In [93]:
# users['Our_Score'] = users['followers_count'] * 0.48 + users['friends_count'] * 0.26 + users['statuses_count'] * 0.26
skfolds = StratifiedKFold(n_splits=3, random_state=42)
train_set, test_set = train_test_split(myusers, test_size=0.2, random_state=42)
X_train = train_set.iloc[:,[0,1,2,4]]
Y_train = train_set['verified']

for train_index, test_index in skfolds.split(X_train, Y_train):
    forest_clf = RandomForestClassifier(random_state=42, n_estimators=30)
    X_train_folds = X_train.iloc[train_index]
    y_train_folds = (Y_train.iloc[train_index])
    X_test_fold = X_train.iloc[test_index]
    y_test_fold = (Y_train.iloc[test_index])
    
    forest_clf = forest_clf.fit(X_train,Y_train)
    y_pred = forest_clf.predict(X_test_fold)
    print(forest_clf.feature_importances_)
    print(confusion_matrix(y_test_fold, y_pred))
    print("Precision Score: ", precision_score(y_test_fold, y_pred))
    print("Recall Score:", recall_score(y_test_fold, y_pred))
    print("Average Precision Score", average_precision_score(y_test_fold, y_pred))
    

[0.46235234 0.24090841 0.23485754 0.06188171]
[[28494     0]
 [   11   512]]
('Precision Score: ', 1.0)
('Recall Score:', 0.9789674952198852)
('Average Precision Score', 0.9793465833406421)
[0.46235234 0.24090841 0.23485754 0.06188171]
[[28493     0]
 [   12   510]]
('Precision Score: ', 1.0)
('Recall Score:', 0.9770114942528736)
('Average Precision Score', 0.9774250734360547)
[0.46235234 0.24090841 0.23485754 0.06188171]
[[28492     1]
 [    9   513]]
('Precision Score: ', 0.9980544747081712)
('Recall Score:', 0.9827586206896551)
('Average Precision Score', 0.9811568233247264)


In [116]:
myusers['myScore'] = ((myusers['followers_count'] + abs(myusers.min()[0])) / \
                    (myusers['friends_count'] + abs(myusers.min()[1]) + 1)) * 55 + \
                    myusers['statuses_count'] * 35 + \
                    myusers['Account Age'] * 10
myusers

followers_count  friends_count  statuses_count  verified  \
screen_name                                                                 
Bryce__Foster          -0.038808      -0.038400       -0.334552         0   
tmj_FLD_HRTA           -0.039532      -0.048665       -0.386069         0   
tmj_BHM_adm            -0.040450      -0.048010       -0.389247         0   
tmj_AZS_adm            -0.039991      -0.049174       -0.387764         0   
HIKARENLALA            -0.042675      -0.067520       -0.299399         0   
tmj_TUL_adm            -0.040327      -0.048010       -0.389271         0   
tmj_KYL_retail         -0.039497      -0.046772       -0.384468         0   
tmj_MTP_retail         -0.039832      -0.047063       -0.389035         0   
todd_malone            -0.042340      -0.048810       -0.373872         0   
jurispotts             -0.039868      -0.034105       -0.385150         0   
xobreyannaa            -0.031391      -0.037308       -0.320920         0   
beekcarroll            -0.037466      -0.043205       -0.347102         0   
VillaAleee             -0.039038      -0.047573        0.175127         0   
Angela_Cusack           0.357207       1.313850       -0.356661         0   
fkn_rndy               -0.036053      -0.049393        0.584645         0   
SPEAKINGOFQUAN         -0.032416       0.048814       -0.262387         0   
ZeiglerHunter          -0.034782      -0.035998       -0.314398         0   
AmberVictoria__        -0.038914      -0.049611        0.090435         0   
MarlenAlvarez11        -0.039550      -0.052014       -0.021662         0   
KrayShawnBrewer        -0.035841      -0.058274       -0.290076         0   
sav_wallace            -0.038296      -0.053542        0.260313         0   
ItsEmCamacho           -0.032981       0.003096        0.734533         0   
J_Kinzler9             -0.035577      -0.042113       -0.053307         0   
Cancertarius           -0.045095      -0.057983       -0.359345         0   
vanessa_cahue          -0.038684      -0.040730       -0.335800         0   
TrinityonMain          -0.039338      -0.056381       -0.374296         0   
Aliyahchico            -0.036265      -0.037454       -0.375050         0   
LanaButton             -0.023833       0.024572       -0.326358         0   
justin_mccall11        -0.029890       0.002877       -0.330267         0   
BraxtonParmer          -0.029608       0.295531        0.177622         0   
...                          ...            ...             ...       ...   
tmj_KSW_adm            -0.040415      -0.047864       -0.389388         0   
AleceaComer            -0.035365      -0.002437       -0.365302         0   
Chef_Shaq              -0.031515      -0.003529       -0.197567         0   
CozyCatCottage         -0.041545      -0.062060       -0.379052         0   
BosworthIII            -0.042834      -0.053688       -0.347125         0   
victortrac             -0.030932      -0.047864       -0.228647         0   
tmj_FLF_retail         -0.037996      -0.046845       -0.376038         0   
tmj_NVC_HRTA           -0.040203      -0.048446       -0.389271         0   
tmj_IAD_HRTA           -0.039850      -0.048446       -0.385951         0   
Darain2000             -0.041704      -0.025442       -0.286897         0   
tmj_MIT_retail         -0.038773      -0.046918       -0.381783         0   
tmj_FLF_HRTA           -0.037590      -0.048301       -0.362618         0   
fasolamatt             -0.036654      -0.032066       -0.171432         0   
SweetScience_          -0.033457       0.014016       -0.232273         0   
mia33178               -0.041934      -0.025442       -0.334811         0   
raulcubilla             1.289996      -0.060531       -0.332127         0   
QueenZK_                0.016958      -0.026825        2.471848         0   
karmicrootsyoga        -0.043858      -0.050630       -0.375497         0   
otischam               -0.035806      -0.034978       -0.359510         0   
garlandtodd08

In [117]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import explained_variance_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

train_set, test_set = train_test_split(myusers, test_size=0.2, random_state=42)

X_train = train_set.iloc[:,[0,1,2,6]]
Y_train = train_set['klout_score']
X_test = test_set.iloc[:,[0,1,2,6]]
Y_test = test_set['klout_score']

forest_clf = RandomForestRegressor(random_state=42, n_estimators=100,n_jobs=-1,min_samples_leaf=30)
forest_clf = forest_clf.fit(X_train,Y_train)
y_pred = forest_clf.predict(X_test)

print(forest_clf.feature_importances_)


[0.81863446 0.03604879 0.07890616 0.06641059]


In [118]:
r2_score(Y_test, y_pred)

0.559483929758272

In [ ]:
x = Y_test - y_pred
print("Accuracy : {0}%".format(len(x[numpy.absolute(x) == 0])*100.0 / len(x)))
print("Accuracy +- 1: {0}%".format(len(x[numpy.absolute(x) == 1])*100.0 / len(x)))
print("Accuracy +- 2: {0}%".format(len(x[numpy.absolute(x) == 2])*100.0 / len(x)))

print "    ",
for i in range(1,10):
    print "{0}   ".format(i),
print ""
print(confusion_matrix(Y_test, y_pred))

In [ ]:
import itertools
import numpy as np
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

# Compute confusion matrix
cnf_matrix = confusion_matrix(Y_test, y_pred)
np.set_printoptions(precision=2)

# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=range(1,10),
                      title='Confusion matrix, without normalization')

# Plot normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=range(1,10), normalize=True,
                      title='Normalized confusion matrix')

plt.show()

In [92]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import explained_variance_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

train_set, test_set = train_test_split(users, test_size=0.2, random_state=42)

X_train = train_set.iloc[:,[0,1,2]]
Y_train = train_set['klout_score'] > 40
X_test = test_set.iloc[:,[0,1,2]]
Y_test = test_set['klout_score'] > 40

forest_clf = RandomForestClassifier(random_state=42, n_estimators=100,n_jobs=-1,min_samples_leaf=100,
                                    max_depth=3, min_impurity_decrease = 0.001)
forest_clf = forest_clf.fit(X_train,Y_train)
y_pred = forest_clf.predict(X_test)

print(forest_clf.feature_importances_)
print(confusion_matrix(Y_test, y_pred))
print("Precision Score: ", precision_score(Y_test, y_pred))
print("Recall Score:", recall_score(Y_test, y_pred))
print("Average Precision Score", average_precision_score(Y_test, y_pred))

[0.51 0.26 0.23]
[[7939 3365]
 [2710 7077]]
('Precision Score: ', 0.6777437272553151)
('Recall Score:', 0.7231020741800347)
('Average Precision Score', 0.6185687204114059)


In [180]:
tweetsDuringEvent = pd.read_sql("SELECT * FROM tweetCoords WHERE CREATED_AT >= DATE('2017-09-10') AND CREATED_AT <= DATE('2017-09-12')", myDB)

In [181]:
tweetsDuringEvent

tweet_id          created_at  \
0      906668545542680576 2017-09-10 00:00:01   
1      906668555185291265 2017-09-10 00:00:03   
2      906668556493889536 2017-09-10 00:00:03   
3      906668570079309830 2017-09-10 00:00:06   
4      906668576056246278 2017-09-10 00:00:08   
5      906668586793660416 2017-09-10 00:00:10   
6      906668589385764864 2017-09-10 00:00:11   
7      906668590878871555 2017-09-10 00:00:11   
8      906668595358216192 2017-09-10 00:00:12   
9      906668601817669632 2017-09-10 00:00:14   
10     906668602086092802 2017-09-10 00:00:14   
11     906668609484849152 2017-09-10 00:00:16   
12     906668642556936192 2017-09-10 00:00:24   
13     906668644670865409 2017-09-10 00:00:24   
14     906668645220220928 2017-09-10 00:00:24   
15     906668658579185664 2017-09-10 00:00:27   
16     906668698290868224 2017-09-10 00:00:37   
17     906668702124449794 2017-09-10 00:00:38   
18     906668714686377985 2017-09-10 00:00:41   
19     906668734672142337 2017-09-10 00:00:46   
20     906668745283723264 2017-09-10 00:00:48   
21     906668751558463488 2017-09-10 00:00:50   
22     906668754808987648 2017-09-10 00:00:50   
23     906668761163366400 2017-09-10 00:00:52   
24     906668810547220480 2017-09-10 00:01:04   
25     906668821821497350 2017-09-10 00:01:06   
26     906668829392216066 2017-09-10 00:01:08   
27     906668830847639553 2017-09-10 00:01:09   
28     906668844764278784 2017-09-10 00:01:12   
29     906668854998454272 2017-09-10 00:01:14   
...                   ...                 ...   
39244  907392727305908224 2017-09-11 23:57:39   
39245  907392777582981121 2017-09-11 23:57:51   
39246  907392813301673984 2017-09-11 23:57:59   
39247  907392816250101760 2017-09-11 23:58:00   
39248  907392852845404160 2017-09-11 23:58:09   
39249  907392866187653121 2017-09-11 23:58:12   
39250  907392889923055622 2017-09-11 23:58:18   
39251  907392912018825216 2017-09-11 23:58:23   
39252  907392919035957248 2017-09-11 23:58:25   
39253  907392926896021504 2017-09-11 23:58:26   
39254  907392955660546051 2017-09-11 23:58:33   
39255  907392987646369792 2017-09-11 23:58:41   
39256  907393003907579905 2017-09-11 23:58:45   
39257  907393024518483969 2017-09-11 23:58:50   
39258  907393026372272128 2017-09-11 23:58:50   
39259  907393028263960576 2017-09-11 23:58:51   
39260  907393030075961344 2017-09-11 23:58:51   
39261  907393062858629121 2017-09-11 23:58:59   
39262  907393080504078336 2017-09-11 23:59:03   
39263  907393095800684544 2017-09-11 23:59:07   
39264  907393116637888512 2017-09-11 23:59:12   
39265  907393125848514560 2017-09-11 23:59:14   
39266  907393177421701120 2017-09-11 23:59:26   
39267  907393191795675136 2017-09-11 23:59:30   
39268  907393212293238785 2017-09-11 23:59:35   
39269  907393229502513152 2017-09-11 23:59:39   
39270  907393263522471936 2017-09-11 23:59:47   
39271  907393277472727040 2017-09-11 23:59:50   
39272  907393295738966016 2017-09-11 23:59:54   
39273  907393309693411329 2017-09-11 23:59:58   

                                                    text             user_id  \
0      Wind 2.0 mph N. Barometer 29.880 in, Steady. T...          1227982520   
1      There is always beauty regardless the circumst...            42239064   
2      #Carpool #Orlando - gt  #Orlando #KIrkmanRoad ...            87188071   
3      @avictoria_x nah i m chillin my eyes never get...           746764728   
4        @jvnvy @sza That s how I feel bout seein travis          1679199278   
5      Taking a beak from boarding the windows. Kitty...            33160615   
6      19:53 Temp. 82.4 F, Hum. 79 , Dewp. 73.6 F, Ba...            19511251   
7      I m so proud of our local radio, news, animal ...           328572345   
8      Evening of a Hurricane. #hurricane #hurricanei...           278782686   
9               hey big head     https://t.co/M46uNJoxx2          2661138289   
10     Deplorable: deplorable nation : please pray fo...  777791864552521728   
11       All I ve 

In [182]:
allImages = getallimages(tweetsDuringEvent.loc[tweetsDuringEvent['image_url'].notnull()]['image_url'].values)

In [20]:
newUsers = pd.read_sql("SELECT user_id, followers_count, friends_count, statuses_count, idsc.score, verified, infes.*, infrs.* FROM myInfluencees infes JOIN myInfluencers infrs on infes.user = infrs.user JOIN klout_id_score idsc on infes.user = idsc.id JOIN user u on u.screen_name = idsc.screen_name where idsc.screen_name in (SELECT screen_name from user);", myDB, index_col='user_id')

In [21]:
newUsers = newUsers.drop(axis=1, columns='user')

In [22]:
newUsers

followers_count  friends_count  statuses_count      score  \
user_id                                                                 
1000029698              379            411            2332  38.379501   
100003413               286            279               9  19.431200   
100003539               312            263              72  31.159500   
1000061430              160             11            3825  24.195400   
100008086               293            279               8  27.871901   
1000089342              179            268             662  30.531000   
1000093178              319            470             183  26.388700   
1000120868              366            285           23979  41.343899   
1000132536            22805          18986            1393  41.569901   
1000138237              535            260           41372  45.686001   
100016468               741           1609            5397  37.375198   
1000180506              607            444            3188  22.751801   
100018195               373            257           20382  40.171101   
1000183748              337            224           15621  32.008099   
1000198212              547            138            4221  41.764500   
1000216416              408            203           27597  36.260101   
1000229666              562            360           14277  37.704498   
100024320                23            142            1279  14.054500   
1000284596              386            379            2279  29.948700   
1000314576              523            424             612  25.812201   
100034510              1227           1276            2680  44.697498   
1000362114              884            978            2514  41.395802   
1000403852              900           4998           24085  41.693802   
1000433094              486            542            4860  43.691799   
1000434721             1032           1331           38496  41.746799   
1000439791              226            290            4940  23.876900   
1000463916              363            181            4163  28.817200   
1000466028              434            333              94  47.492699   
100046855               320            267             428  32.407902   
100046930               277            260              16  27.115801   
...                     ...            ...             ...        ...   
99890148               2194            987           56695  44.951302   
9989362               14476            361           55778  54.189602   
99893656               1667            950           46824  32.639500   
9989972                 168            558             533  29.899700   
999104456               242            149            2449  38.243599   
999439278               620            544            1917  27.137600   
999473420               484            821           10812  37.233101   
999493028               574            905            1026  23.773600   
999494336               792            890            8150  36.087101   
999544040               224             86             442  37.353100   
999553783               151            201            1798  16.511600   
999621                  825            281            6830  45.860699   
999645158               215            589            4356  31.756500   
99966321                501            498            9260  45.899502   
99967117                682           1131            6676  41.120800   
999681846               202            589            2321  29.545900   
99968701              75628            107            2435  50.151402   
999691736              3537            570          121525  50.762600   
99971587                 93            243             593  28.365299   
999746082               549            458            1272  25.030701   
999764695               458            512            5618  32.133301   
999837722              1573            967           28702  48.826099 

In [12]:
newUsers.describe()

followers_count  friends_count  statuses_count      verified  \
count     8.507800e+04   8.507800e+04    8.507800e+04  85078.000000   
mean      2.890145e+03   1.024349e+03    1.788785e+04      0.020170   
std       6.110665e+04   1.589826e+04    4.512953e+04      0.140581   
min       0.000000e+00   0.000000e+00    1.000000e+00      0.000000   
25%       2.410000e+02   2.640000e+02    2.507000e+03      0.000000   
50%       5.190000e+02   4.900000e+02    7.801500e+03      0.000000   
75%       1.105000e+03   9.190000e+02    2.025100e+04      0.000000   
max       1.312178e+07   4.358008e+06    9.395746e+06      1.000000   

       influencees_count  influencers_count  
count       85078.000000       85078.000000  
mean            4.682938           4.942817  
std             2.271799           0.916285  
min             1.000000           1.000000  
25%             5.000000           5.000000  
50%             5.000000           5.000000  
75%             5.000000           5.000000  
max           342.000000          61.000000

In [23]:
newUsers.corr()

followers_count  friends_count  statuses_count     score  \
followers_count           1.000000       0.278782        0.025744  0.107872   
friends_count             0.278782       1.000000        0.039508  0.055593   
statuses_count            0.025744       0.039508        1.000000  0.219076   
score                     0.107872       0.055593        0.219076  1.000000   
verified                  0.164156       0.048354        0.037105  0.297336   
influencees_count         0.117712       0.011719        0.053792  0.235171   
influencers_count        -0.001530       0.000789        0.053411  0.051058   

                   verified  influencees_count  influencers_count  
followers_count    0.164156           0.117712          -0.001530  
friends_count      0.048354           0.011719           0.000789  
statuses_count     0.037105           0.053792           0.053411  
score              0.297336           0.235171           0.051058  
verified           1.000000           0.098636          -0.005190  
influencees_count  0.098636           1.000000           0.243507  
influencers_count -0.005190           0.243507           1.000000

In [24]:
xUsers = newUsers.copy()

In [25]:
xUsers[xUsers.columns[5:]] = xUsers[xUsers.columns[5:]].astype(float)

In [26]:
xUsers.corr()

followers_count  friends_count  statuses_count     score  \
followers_count           1.000000       0.278782        0.025744  0.107872   
friends_count             0.278782       1.000000        0.039508  0.055593   
statuses_count            0.025744       0.039508        1.000000  0.219076   
score                     0.107872       0.055593        0.219076  1.000000   
verified                  0.164156       0.048354        0.037105  0.297336   
influencees_std           0.012754       0.005527       -0.047870  0.012966   
influencees_avg           0.002621       0.017770        0.100407  0.331899   
influencees_max           0.017096       0.019143        0.056050  0.274787   
influencees_min          -0.011650       0.008173        0.102066  0.212845   
influencees_count         0.117712       0.011719        0.053792  0.235171   
influencers_std          -0.008412      -0.006061       -0.038967 -0.142359   
influencers_avg           0.002655       0.001549       -0.029821 -0.089121   
influencers_max          -0.001650      -0.002180       -0.039301 -0.114463   
influencers_min           0.007776       0.003806        0.001227  0.041048   
influencers_count        -0.001530       0.000789        0.053411  0.051058   

                   verified  influencees_std  influencees_avg  \
followers_count    0.164156         0.012754         0.002621   
friends_count      0.048354         0.005527         0.017770   
statuses_count     0.037105        -0.047870         0.100407   
score              0.297336         0.012966         0.331899   
verified           1.000000         0.049422         0.062244   
influencees_std    0.049422         1.000000         0.014825   
influencees_avg    0.062244         0.014825         1.000000   
influencees_max    0.090512         0.580471         0.773353   
influencees_min    0.011149        -0.567946         0.759275   
influencees_count  0.098636         0.163751         0.085227   
influencers_std   -0.030217         0.101332        -0.140265   
influencers_avg    0.008435         0.168769         0.072372   
influencers_max   -0.000479         0.191061         0.012738   
influencers_min    0.032824         0.060361         0.163550   
influencers_count -0.005190         0.175886         0.061528   

                   influencees_max  influencees_min  influencees_count  \
followers_count           0.017096        -0.011650           0.117712   
friends_count             0.019143         0.008173           0.011719   
statuses_count            0.056050         0.102066           0.053792   
score                     0.274787         0.212845           0.235171   
verified                  0.090512         0.011149           0.098636   
influencees_std           0.580471        -0.567946           0.163751   
influencees_avg           0.773353         0.759275           0.085227   
influencees_max           1.000000         0.310814           0.192056   
influencees_min           0.310814         1.000000          -0.071473   
influencees_count         0.192056        -0.071473           1.000000   
influencers_std          -0.045379        -0.162397           0.043415   
influencers_avg           0.153860        -0.037685           0.037642   
influencers_max           0.122658        -0.098395           0.071861   
influencers_min           0.157788         0.089648           0.010043   
influencers_count         0.155065        -0.072817           0.243507   

                   influencers_std  influencers_avg  influencers_max  \
followers_count          -0.008412         0.002655        -0.001650   
friends_count            -0.006061         0.001549        -0.002180   
statuses_count           -0.038967        -0.029821        -0.039301   
score                    -0.142359        -0.089121        -0.114463   
verified                 -0.030217         0.008435        -0.000479   
influencees_std           0.101332         0.168769         0.191061   
influencees_avg         

In [118]:
tweetText = pd.read_sql("SELECT tweet_id,text from tweetCoords", getDBInstance('geotwitter'), index_col='tweet_id')

In [188]:
tweetText.to_csv("tweetsText.csv")

In [122]:
myTweets = pd.read_sql("SELECT * FROM polished_tweets", getDBInstance('geotwitter'), index_col='tweet_id')

In [176]:
import re
def getLinks(texts):
    ans = []
    for text in texts:
        ans.append(len(re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', text)) != 0)
    return ans

In [177]:
myTweets['has_url'] = getLinks(myTweets['text'])

In [180]:
myTweets.has_hashtags = myTweets.has_hashtags == 1

In [181]:
myTweets.has_image = myTweets.has_image == 1

In [183]:
myTweets = myTweets[['text','created_at','user_id','latitude','longitude','has_image','has_hashtags','has_url','image_url']]

In [186]:
myTweets = myTweets.drop(axis=1, columns=['text','created_at','user_id','latitude','longitude','image_url'])

In [194]:
myTweets.to_sql(con=engine,name='tweetFeatures',index=False)

In [191]:
myTweets['tweet_id'] = myTweets.index